[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = ["npm install --production || true"]

[phases.build]
cmds = ["chmod +x railway-deploy.sh"]

[start]
cmd = "sh railway-deploy.sh"